version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "8081:80"
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    links:
      - php
    depends_on:
      - php
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    links:
      - mysql
      - redis
    depends_on:
      - mysql

  mysql:
    image: mysql:5.6
    hostname: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_USER=${DB_USERNAME}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
    volumes:
      - data-volume:/var/lib/mysql
    restart: always

  redis:
    image: redis
    hostname: redis

  #worker:
  #  image: php:7.2-cli
  #  volumes:
  #    - ./:/var/www
  #  links:
  #    - mysql
  #  working_dir: /var/www
  #  command: bash -c "apt-get update && docker-php-ext-install pdo_mysql && php artisan queue:work redis --sleep=1 --tries=1"
  #  depends_on:
  #    - php
  #  restart: always


  #frontend:
  #  image: node:8-alpine
  #  hostname: frontend
  #  ports:
  #    - "8088:8088"
  #  volumes:
  #    - ./laravel-echo-server.json:/usr/src/app/laravel-echo-server.json
  #    - ./:/var/www
  #  working_dir: /usr/src/app
  #  command: bash -c "npm install -g laravel-echo-server && /usr/local/lib/node_modules/laravel-echo-server/bin/server.js start"
  #  depends_on:
  #    - redis
  #  restart: always


  #laravel_echo_server:
  #  image: node:boron
  #  hostname: laravel-echo-server
  #  ports:
  #    - "6001:6001"
  #  volumes:
  #    - ./laravel-echo-server.json:/usr/src/app/laravel-echo-server.json
  #    - ./:/var/www
  #  working_dir: /usr/src/app
  #  command: bash -c "npm install -g laravel-echo-server && /usr/local/lib/node_modules/laravel-echo-server/bin/server.js start"
  #  depends_on:
  #    - redis
  #  restart: always

volumes:
  data-volume:
    driver: local
